INFO:django.utils.autoreload:Watching for file changes with StatReloader
INFO:django.utils.autoreload:Watching for file changes with StatReloader
ERROR:root:File not found: media/news/elon2_14.png
ERROR:root:File not found: media/news/moon_4k_8k-3840x2160.jpg
ERROR:root:File not found: media/news/IMG_20230620_230638_641.jpg
INFO:django.utils.autoreload:D:\Python\MyProjects\TIIAME_NRU\apps\News\signals.py changed, reloading.
INFO:django.utils.autoreload:Watching for file changes with StatReloader
ERROR:django.request:Internal Server Error: /tiiame/admin/News/news/add/
Traceback (most recent call last):
  File "D:\Python\MyProjects\TIIAME_NRU\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\Python\MyProjects\TIIAME_NRU\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Python\MyProjects\TIIAME_NRU\venv\lib\site-packages\django\contrib\admin\options.py", line 714, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "D:\Python\MyProjects\TIIAME_NRU\venv\lib\site-packages\django\utils\decorators.py", line 188, in _view_wrapper
    result = _process_exception(request, e)
  File "D:\Python\MyProjects\TIIAME_NRU\venv\lib\site-packages\django\utils\decorators.py", line 186, in _view_wrapper
    response = view_func(request, *args, **kwargs)
  File "D:\Python\MyProjects\TIIAME_NRU\venv\lib\site-packages\django\views\decorators\cache.py", line 80, in _view_wrapper
    response = view_func(request, *args, **kwargs)
  File "D:\Python\MyProjects\TIIAME_NRU\venv\lib\site-packages\django\contrib\admin\sites.py", line 240, in inner
    return view(request, *args, **kwargs)
  File "D:\Python\MyProjects\TIIAME_NRU\venv\lib\site-packages\django\contrib\admin\options.py", line 1941, in add_view
    return self.changeform_view(request, None, form_url, extra_context)
  File "D:\Python\MyProjects\TIIAME_NRU\venv\lib\site-packages\django\utils\decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
  File "D:\Python\MyProjects\TIIAME_NRU\venv\lib\site-packages\django\utils\decorators.py", line 188, in _view_wrapper
    result = _process_exception(request, e)
  File "D:\Python\MyProjects\TIIAME_NRU\venv\lib\site-packages\django\utils\decorators.py", line 186, in _view_wrapper
    response = view_func(request, *args, **kwargs)
  File "D:\Python\MyProjects\TIIAME_NRU\venv\lib\site-packages\django\contrib\admin\options.py", line 1802, in changeform_view
    return self._changeform_view(request, object_id, form_url, extra_context)
  File "D:\Python\MyProjects\TIIAME_NRU\venv\lib\site-packages\django\contrib\admin\options.py", line 1853, in _changeform_view
    self.save_model(request, new_object, form, not add)
  File "D:\Python\MyProjects\TIIAME_NRU\venv\lib\site-packages\django\contrib\admin\options.py", line 1257, in save_model
    obj.save()
  File "D:\Python\MyProjects\TIIAME_NRU\venv\lib\site-packages\django\db\models\base.py", line 822, in save
    self.save_base(
  File "D:\Python\MyProjects\TIIAME_NRU\venv\lib\site-packages\django\db\models\base.py", line 924, in save_base
    post_save.send(
  File "D:\Python\MyProjects\TIIAME_NRU\venv\lib\site-packages\django\dispatch\dispatcher.py", line 189, in send
    response = receiver(signal=self, sender=sender, **named)
  File "D:\Python\MyProjects\TIIAME_NRU\apps\News\signals.py", line 19, in news_post_save
    loop = asyncio.get_event_loop()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\asyncio\events.py", line 656, in get_event_loop
    raise RuntimeError('There is no current event loop in thread %r.'
RuntimeError: There is no current event loop in thread 'Thread-1 (process_request_thread)'.
WARNING:django.request:Not Found: /favicon.ico
INFO:django.utils.autoreload:D:\Python\MyProjects\TIIAME_NRU\apps\News\signals.py changed, reloading.
INFO:django.utils.autoreload:Watching for file changes with StatReloader
INFO:django.utils.autoreload:Watching for file changes with StatReloader
INFO:django.utils.autoreload:D:\Python\MyProjects\TIIAME_NRU\apps\News\signals.py changed, reloading.
INFO:django.utils.autoreload:Watching for file changes with StatReloader
ERROR:root:File not found: media/news/Frame_skjwvrv_FQz6LT6.png
INFO:django.utils.autoreload:D:\Python\MyProjects\TIIAME_NRU\apps\News\signals.py changed, reloading.
INFO:django.utils.autoreload:Watching for file changes with StatReloader
INFO:django.utils.autoreload:Watching for file changes with StatReloader
INFO:django.utils.autoreload:D:\Python\MyProjects\TIIAME_NRU\apps\News\signals.py changed, reloading.
INFO:django.utils.autoreload:Watching for file changes with StatReloader
INFO:django.utils.autoreload:D:\Python\MyProjects\TIIAME_NRU\apps\News\signals.py changed, reloading.
INFO:django.utils.autoreload:Watching for file changes with StatReloader
INFO:django.utils.autoreload:Watching for file changes with StatReloader
INFO:django.utils.autoreload:D:\Python\MyProjects\TIIAME_NRU\Bot\main.py changed, reloading.
INFO:django.utils.autoreload:Watching for file changes with StatReloader
INFO:django.utils.autoreload:D:\Python\MyProjects\TIIAME_NRU\Bot\main.py changed, reloading.
INFO:django.utils.autoreload:Watching for file changes with StatReloader
INFO:django.utils.autoreload:Watching for file changes with StatReloader
INFO:django.utils.autoreload:D:\Python\MyProjects\TIIAME_NRU\apps\News\signals.py changed, reloading.
INFO:django.utils.autoreload:Watching for file changes with StatReloader
ERROR:django.request:Internal Server Error: /tiiame/admin/News/news/add/
Traceback (most recent call last):
  File "D:\Python\MyProjects\TIIAME_NRU\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\Python\MyProjects\TIIAME_NRU\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Python\MyProjects\TIIAME_NRU\venv\lib\site-packages\django\contrib\admin\options.py", line 714, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "D:\Python\MyProjects\TIIAME_NRU\venv\lib\site-packages\django\utils\decorators.py", line 188, in _view_wrapper
    result = _process_exception(request, e)
  File "D:\Python\MyProjects\TIIAME_NRU\venv\lib\site-packages\django\utils\decorators.py", line 186, in _view_wrapper
    response = view_func(request, *args, **kwargs)
  File "D:\Python\MyProjects\TIIAME_NRU\venv\lib\site-packages\django\views\decorators\cache.py", line 80, in _view_wrapper
    response = view_func(request, *args, **kwargs)
  File "D:\Python\MyProjects\TIIAME_NRU\venv\lib\site-packages\django\contrib\admin\sites.py", line 240, in inner
    return view(request, *args, **kwargs)
  File "D:\Python\MyProjects\TIIAME_NRU\venv\lib\site-packages\django\contrib\admin\options.py", line 1941, in add_view
    return self.changeform_view(request, None, form_url, extra_context)
  File "D:\Python\MyProjects\TIIAME_NRU\venv\lib\site-packages\django\utils\decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
  File "D:\Python\MyProjects\TIIAME_NRU\venv\lib\site-packages\django\utils\decorators.py", line 188, in _view_wrapper
    result = _process_exception(request, e)
  File "D:\Python\MyProjects\TIIAME_NRU\venv\lib\site-packages\django\utils\decorators.py", line 186, in _view_wrapper
    response = view_func(request, *args, **kwargs)
  File "D:\Python\MyProjects\TIIAME_NRU\venv\lib\site-packages\django\contrib\admin\options.py", line 1802, in changeform_view
    return self._changeform_view(request, object_id, form_url, extra_context)
  File "D:\Python\MyProjects\TIIAME_NRU\venv\lib\site-packages\django\contrib\admin\options.py", line 1853, in _changeform_view
    self.save_model(request, new_object, form, not add)
  File "D:\Python\MyProjects\TIIAME_NRU\venv\lib\site-packages\django\contrib\admin\options.py", line 1257, in save_model
    obj.save()
  File "D:\Python\MyProjects\TIIAME_NRU\venv\lib\site-packages\django\db\models\base.py", line 822, in save
    self.save_base(
  File "D:\Python\MyProjects\TIIAME_NRU\venv\lib\site-packages\django\db\models\base.py", line 924, in save_base
    post_save.send(
  File "D:\Python\MyProjects\TIIAME_NRU\venv\lib\site-packages\django\dispatch\dispatcher.py", line 189, in send
    response = receiver(signal=self, sender=sender, **named)
  File "D:\Python\MyProjects\TIIAME_NRU\apps\News\signals.py", line 12, in news_post_save
    loop = asyncio.get_event_loop()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\asyncio\events.py", line 656, in get_event_loop
    raise RuntimeError('There is no current event loop in thread %r.'
RuntimeError: There is no current event loop in thread 'Thread-1 (process_request_thread)'.
INFO:django.utils.autoreload:D:\Python\MyProjects\TIIAME_NRU\apps\News\signals.py changed, reloading.
INFO:django.utils.autoreload:Watching for file changes with StatReloader
ERROR:django.request:Internal Server Error: /tiiame/admin/News/news/add/
Traceback (most recent call last):
  File "D:\Python\MyProjects\TIIAME_NRU\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\Python\MyProjects\TIIAME_NRU\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Python\MyProjects\TIIAME_NRU\venv\lib\site-packages\django\contrib\admin\options.py", line 714, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "D:\Python\MyProjects\TIIAME_NRU\venv\lib\site-packages\django\utils\decorators.py", line 188, in _view_wrapper
    result = _process_exception(request, e)
  File "D:\Python\MyProjects\TIIAME_NRU\venv\lib\site-packages\django\utils\decorators.py", line 186, in _view_wrapper
    response = view_func(request, *args, **kwargs)
  File "D:\Python\MyProjects\TIIAME_NRU\venv\lib\site-packages\django\views\decorators\cache.py", line 80, in _view_wrapper
    response = view_func(request, *args, **kwargs)
  File "D:\Python\MyProjects\TIIAME_NRU\venv\lib\site-packages\django\contrib\admin\sites.py", line 240, in inner
    return view(request, *args, **kwargs)
  File "D:\Python\MyProjects\TIIAME_NRU\venv\lib\site-packages\django\contrib\admin\options.py", line 1941, in add_view
    return self.changeform_view(request, None, form_url, extra_context)
  File "D:\Python\MyProjects\TIIAME_NRU\venv\lib\site-packages\django\utils\decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
  File "D:\Python\MyProjects\TIIAME_NRU\venv\lib\site-packages\django\utils\decorators.py", line 188, in _view_wrapper
    result = _process_exception(request, e)
  File "D:\Python\MyProjects\TIIAME_NRU\venv\lib\site-packages\django\utils\decorators.py", line 186, in _view_wrapper
    response = view_func(request, *args, **kwargs)
  File "D:\Python\MyProjects\TIIAME_NRU\venv\lib\site-packages\django\contrib\admin\options.py", line 1802, in changeform_view
    return self._changeform_view(request, object_id, form_url, extra_context)
  File "D:\Python\MyProjects\TIIAME_NRU\venv\lib\site-packages\django\contrib\admin\options.py", line 1853, in _changeform_view
    self.save_model(request, new_object, form, not add)
  File "D:\Python\MyProjects\TIIAME_NRU\venv\lib\site-packages\django\contrib\admin\options.py", line 1257, in save_model
    obj.save()
  File "D:\Python\MyProjects\TIIAME_NRU\venv\lib\site-packages\django\db\models\base.py", line 822, in save
    self.save_base(
  File "D:\Python\MyProjects\TIIAME_NRU\venv\lib\site-packages\django\db\models\base.py", line 924, in save_base
    post_save.send(
  File "D:\Python\MyProjects\TIIAME_NRU\venv\lib\site-packages\django\dispatch\dispatcher.py", line 189, in send
    response = receiver(signal=self, sender=sender, **named)
  File "D:\Python\MyProjects\TIIAME_NRU\apps\News\signals.py", line 12, in news_post_save
    loop = asyncio.get_event_loop()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\asyncio\events.py", line 656, in get_event_loop
    raise RuntimeError('There is no current event loop in thread %r.'
RuntimeError: There is no current event loop in thread 'Thread-1 (process_request_thread)'.
INFO:django.utils.autoreload:D:\Python\MyProjects\TIIAME_NRU\apps\News\signals.py changed, reloading.
INFO:django.utils.autoreload:Watching for file changes with StatReloader
INFO:django.utils.autoreload:Watching for file changes with StatReloader
INFO:django.utils.autoreload:D:\Python\MyProjects\TIIAME_NRU\apps\News\signals.py changed, reloading.
ERROR:asyncio:Fatal error on SSL transport
protocol: <asyncio.sslproto.SSLProtocol object at 0x000001ECE426F9A0>
transport: <_ProactorSocketTransport fd=832 read=<_OverlappedFuture cancelled>>
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\asyncio\sslproto.py", line 690, in _process_write_backlog
    self._transport.write(chunk)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\asyncio\proactor_events.py", line 365, in write
    self._loop_writing(data=bytes(data))
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\asyncio\proactor_events.py", line 401, in _loop_writing
    self._write_fut = self._loop._proactor.send(self._sock, data)
AttributeError: 'NoneType' object has no attribute 'send'
INFO:django.utils.autoreload:Watching for file changes with StatReloader
INFO:django.utils.autoreload:Watching for file changes with StatReloader
WARNING:django.request:Not Found: /admin/
ERROR:root:File not found: media/news/elon2_14_Nnyx06j.png
ERROR:root:File not found: media/news/elon2_14_Nnyx06j.png
ERROR:root:File not found: media/news/elon2_14_Nnyx06j.png
INFO:django.utils.autoreload:Watching for file changes with StatReloader
WARNING:django.request:Not Found: /admin/
INFO:django.utils.autoreload:Watching for file changes with StatReloader
WARNING:django.request:Not Found: /admin/
ERROR:root:File not found: media/news/YcLbRyGPzSFMaFJ1REY9N_Y9W1Yud_b0.jpg
ERROR:root:File not found: media/news/YcLbRyGPzSFMaFJ1REY9N_Y9W1Yud_b0.jpg
ERROR:root:File not found: media/news/YcLbRyGPzSFMaFJ1REY9N_Y9W1Yud_b0.jpg
INFO:django.utils.autoreload:Watching for file changes with StatReloader
ERROR:root:File not found: media/news/YcLbRyGPzSFMaFJ1REY9N_Y9W1Yud_b0.jpg
INFO:django.utils.autoreload:Watching for file changes with StatReloader
ERROR:root:File not found: media/news/YcLbRyGPzSFMaFJ1REY9N_Y9W1Yud_b0.jpg
INFO:django.utils.autoreload:D:\Python\MyProjects\TIIAME_NRU\apps\News\signals.py changed, reloading.
INFO:django.utils.autoreload:Watching for file changes with StatReloader
INFO:django.utils.autoreload:D:\Python\MyProjects\TIIAME_NRU\Bot\main.py changed, reloading.
INFO:django.utils.autoreload:Watching for file changes with StatReloader
